version: '{branch}-{build}'
build: off
environment:
  global:
    COVERALLS_EXTRAS: '-v'
    COVERALLS_REPO_TOKEN: GvSJKUlHuUxUg43UwNngqvKlJpVKCPMHj
  matrix:
    - TOXENV: check
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    - TOXENV: py27-pytest46-pygal24-nodist-cover,py27-pytest46-pygal24-xdist-cover,codecov,coveralls
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
    - TOXENV: py27-pytest46-pygal24-nodist-cover,py27-pytest46-pygal24-xdist-cover,codecov,coveralls
      TOXPYTHON: C:\Python27-x64\python.exe
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'
      WINDOWS_SDK_VERSION: v7.0
    - TOXENV: py27-pytest46-pygal24-nodist-nocov,py27-pytest46-pygal24-xdist-nocov
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: py27-pytest46-pygal24-nodist-nocov,py27-pytest46-pygal24-xdist-nocov
      TOXPYTHON: C:\Python27-x64\python.exe
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
      WINDOWS_SDK_VERSION: v7.0
    - TOXENV: py36-pytest6-pygal24-nodist-cover,py36-pytest6-pygal24-xdist-cover,codecov,coveralls
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    - TOXENV: py36-pytest6-pygal24-nodist-cover,py36-pytest6-pygal24-xdist-cover,codecov,coveralls
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
    - TOXENV: py36-pytest6-pygal24-nodist-nocov,py36-pytest6-pygal24-xdist-nocov
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: py36-pytest6-pygal24-nodist-nocov,py36-pytest6-pygal24-xdist-nocov
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
    - TOXENV: py37-pytest6-pygal24-nodist-cover,py37-pytest6-pygal24-xdist-cover,codecov,coveralls
      TOXPYTHON: C:\Python37\python.exe
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
    - TOXENV: py37-pytest6-pygal24-nodist-cover,py37-pytest6-pygal24-xdist-cover,codecov,coveralls
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
    - TOXENV: py37-pytest6-pygal24-nodist-nocov,py37-pytest6-pygal24-xdist-nocov
      TOXPYTHON: C:\Python37\python.exe
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: py37-pytest6-pygal24-nodist-nocov,py37-pytest6-pygal24-xdist-nocov
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
    - TOXENV: py38-pytest6-pygal24-nodist-cover,py38-pytest6-pygal24-xdist-cover,codecov,coveralls
      TOXPYTHON: C:\Python38\python.exe
      PYTHON_HOME: C:\Python38
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '32'
    - TOXENV: py38-pytest6-pygal24-nodist-cover,py38-pytest6-pygal24-xdist-cover,codecov,coveralls
      TOXPYTHON: C:\Python38-x64\python.exe
      PYTHON_HOME: C:\Python38-x64
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '64'
    - TOXENV: py38-pytest6-pygal24-nodist-nocov,py38-pytest6-pygal24-xdist-nocov
      TOXPYTHON: C:\Python38\python.exe
      PYTHON_HOME: C:\Python38
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: py38-pytest6-pygal24-nodist-nocov,py38-pytest6-pygal24-xdist-nocov
      TOXPYTHON: C:\Python38-x64\python.exe
      PYTHON_HOME: C:\Python38-x64
      PYTHON_VERSION: '3.8'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
    - TOXENV: py39-pytest6-pygal24-nodist-cover,py39-pytest6-pygal24-xdist-cover,codecov,coveralls
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TOXPYTHON: C:\Python39\python.exe
      PYTHON_HOME: C:\Python39
      PYTHON_VERSION: '3.9'
      PYTHON_ARCH: '32'
    - TOXENV: py39-pytest6-pygal24-nodist-cover,py39-pytest6-pygal24-xdist-cover,codecov,coveralls
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TOXPYTHON: C:\Python39-x64\python.exe
      PYTHON_HOME: C:\Python39-x64
      PYTHON_VERSION: '3.9'
      PYTHON_ARCH: '64'
    - TOXENV: py39-pytest6-pygal24-nodist-nocov,py39-pytest6-pygal24-xdist-nocov
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TOXPYTHON: C:\Python39\python.exe
      PYTHON_HOME: C:\Python39
      PYTHON_VERSION: '3.9'
      PYTHON_ARCH: '32'
      WHEEL_PATH: .tox/dist
    - TOXENV: py39-pytest6-pygal24-nodist-nocov,py39-pytest6-pygal24-xdist-nocov
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TOXPYTHON: C:\Python39-x64\python.exe
      PYTHON_HOME: C:\Python39-x64
      PYTHON_VERSION: '3.9'
      PYTHON_ARCH: '64'
      WHEEL_PATH: .tox/dist
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - '%PYTHON_HOME%\python -mpip install --progress-bar=off tox -rci/requirements.txt'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd %PYTHON_HOME%\Scripts\tox
on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
