language: python
sudo: false
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
  matrix:
    - TOXENV=check
    - TOXENV=docs
matrix:
  include:

    - python: '2.7'
      env:
        - TOXENV=py27-pytest31-pygal23-nodist-cover,report,coveralls,codecov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest31-pygal23-nodist-nocov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest31-pygal23-xdist-cover,report,coveralls,codecov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest31-pygal23-xdist-nocov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest32-pygal23-nodist-cover,report,coveralls,codecov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest32-pygal23-nodist-nocov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest32-pygal23-xdist-cover,report,coveralls,codecov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest32-pygal23-xdist-nocov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest33-pygal23-nodist-cover,report,coveralls,codecov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest33-pygal23-nodist-nocov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest33-pygal23-xdist-cover,report,coveralls,codecov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest33-pygal23-xdist-nocov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest34-pygal23-nodist-cover,report,coveralls,codecov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest34-pygal23-nodist-nocov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest34-pygal23-xdist-cover,report,coveralls,codecov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest34-pygal23-xdist-nocov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest35-pygal23-nodist-cover,report,coveralls,codecov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest35-pygal23-nodist-nocov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest35-pygal23-xdist-cover,report,coveralls,codecov
    - python: '2.7'
      env:
        - TOXENV=py27-pytest35-pygal23-xdist-nocov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest31-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest31-pygal23-nodist-nocov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest31-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest31-pygal23-xdist-nocov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest32-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest32-pygal23-nodist-nocov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest32-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest32-pygal23-xdist-nocov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest33-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest33-pygal23-nodist-nocov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest33-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest33-pygal23-xdist-nocov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest34-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest34-pygal23-nodist-nocov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest34-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest34-pygal23-xdist-nocov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest35-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest35-pygal23-nodist-nocov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest35-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.4'
      env:
        - TOXENV=py34-pytest35-pygal23-xdist-nocov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest31-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest31-pygal23-nodist-nocov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest31-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest31-pygal23-xdist-nocov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest32-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest32-pygal23-nodist-nocov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest32-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest32-pygal23-xdist-nocov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest33-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest33-pygal23-nodist-nocov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest33-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest33-pygal23-xdist-nocov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest34-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest34-pygal23-nodist-nocov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest34-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest34-pygal23-xdist-nocov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest35-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest35-pygal23-nodist-nocov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest35-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.5'
      env:
        - TOXENV=py35-pytest35-pygal23-xdist-nocov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest31-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest31-pygal23-nodist-nocov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest31-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest31-pygal23-xdist-nocov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest32-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest32-pygal23-nodist-nocov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest32-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest32-pygal23-xdist-nocov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest33-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest33-pygal23-nodist-nocov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest33-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest33-pygal23-xdist-nocov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest34-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest34-pygal23-nodist-nocov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest34-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest34-pygal23-xdist-nocov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest35-pygal23-nodist-cover,report,coveralls,codecov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest35-pygal23-nodist-nocov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest35-pygal23-xdist-cover,report,coveralls,codecov
    - python: '3.6'
      env:
        - TOXENV=py36-pytest35-pygal23-xdist-nocov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest31-pygal23-nodist-cover,report,coveralls,codecov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest31-pygal23-nodist-nocov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest31-pygal23-xdist-cover,report,coveralls,codecov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest31-pygal23-xdist-nocov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest32-pygal23-nodist-cover,report,coveralls,codecov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest32-pygal23-nodist-nocov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest32-pygal23-xdist-cover,report,coveralls,codecov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest32-pygal23-xdist-nocov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest33-pygal23-nodist-cover,report,coveralls,codecov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest33-pygal23-nodist-nocov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest33-pygal23-xdist-cover,report,coveralls,codecov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest33-pygal23-xdist-nocov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest34-pygal23-nodist-cover,report,coveralls,codecov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest34-pygal23-nodist-nocov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest34-pygal23-xdist-cover,report,coveralls,codecov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest34-pygal23-xdist-nocov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest35-pygal23-nodist-cover,report,coveralls,codecov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest35-pygal23-nodist-nocov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest35-pygal23-xdist-cover,report,coveralls,codecov
    - python: 'pypy-5.4'
      env:
        - TOXENV=pypy-pytest35-pygal23-xdist-nocov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest31-pygal23-nodist-cover,report,coveralls,codecov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest31-pygal23-nodist-nocov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest31-pygal23-xdist-cover,report,coveralls,codecov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest31-pygal23-xdist-nocov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest32-pygal23-nodist-cover,report,coveralls,codecov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest32-pygal23-nodist-nocov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest32-pygal23-xdist-cover,report,coveralls,codecov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest32-pygal23-xdist-nocov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest33-pygal23-nodist-cover,report,coveralls,codecov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest33-pygal23-nodist-nocov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest33-pygal23-xdist-cover,report,coveralls,codecov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest33-pygal23-xdist-nocov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest34-pygal23-nodist-cover,report,coveralls,codecov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest34-pygal23-nodist-nocov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest34-pygal23-xdist-cover,report,coveralls,codecov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest34-pygal23-xdist-nocov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest35-pygal23-nodist-cover,report,coveralls,codecov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest35-pygal23-nodist-nocov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest35-pygal23-xdist-cover,report,coveralls,codecov
    - python: 'pypy3-5.4'
      env:
        - TOXENV=pypy3-pytest35-pygal23-xdist-nocov
    - python: '2.6'
      env:
        - TOXENV=py26-pytest29-pygal22-nodist-cover,report,coveralls,codecov
    - python: '2.6'
      env:
        - TOXENV=py26-pytest29-pygal22-nodist-nocov
    - python: '3.3'
      env:
        - TOXENV=py33-pytest29-pygal22-nodist-cover,report,coveralls,codecov
    - python: '3.3'
      env:
        - TOXENV=py33-pytest29-pygal22-nodist-nocov
    - python: '3.2'
      env:
        - TOXENV=py32-pytest28
    - python: '3.2'
      env:
        - TOXENV=py32-pytest29
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install -U tox wheel $(if python -V |& grep -q 'Python 3.2'; then echo 'pip<8.0 virtualenv<14.0 setuptools<30.0'; else echo setuptools; fi)
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - |
    set -ex
    if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then
        (cd $HOME
         wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-5.7.1-linux_x86_64-portable.tar.bz2
         tar xf pypy-5.7.1-linux_x86_64-portable.tar.bz2
         pypy-5.7.1-linux_x86_64-portable/bin/pypy -m ensurepip
         pypy-5.7.1-linux_x86_64-portable/bin/pypy -m pip install -U virtualenv)
        export PATH=$HOME/pypy-5.7.1-linux_x86_64-portable/bin/:$PATH
        export TOXPYTHON=$HOME/pypy-5.7.1-linux_x86_64-portable/bin/pypy
    fi
    if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then
        (cd $HOME
         wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.5-5.7.1-beta-linux_x86_64-portable.tar.bz2
         tar xf pypy3.5-5.7.1-beta-linux_x86_64-portable.tar.bz2
         pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/pypy3 -m ensurepip
         pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/pypy3 -m pip install -U virtualenv)
        export PATH=$HOME/pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/:$PATH
        export TOXPYTHON=$HOME/pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/pypy3
    fi
    set +x
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
